/* RPGAtlas - patch-notes.js
   Keep newest entries first. See AGENTS.md for the update policy. */
"use strict";

export function getPatchNotes(t) {
  return [
   {
      date: "June 17, 2026",
      title: "Remoção do Grid-Free Mapping",
      summary: "Sistema de mapeamento livre (Grid-Free) foi removido para simplificar o editor e focar na compatibilidade padrão RMMV. Pixel Movement foi mantido.",
      items: [
        "Lógica de 'tilePlacements' e flag 'gridFree' removida do editor e da engine",
        "Interface de 'snap' e arrasto de tiles livres removida",
        "Física simplificada para focar em colisões baseadas em grade e máscaras livres",
        "Pixel Movement (movimentação por pixel) preservado e funcional",
      ],
   },
   {
      date: "June 17, 2026",
      title: "Sidebar com criação/deleção de tilesets",
      summary: "Sidebar do editor de tilesets agora tem botões '+ New' e 'Delete', permitindo criar e remover tilesets como no RPG Maker.",
      items: [
        "Botão '+ New' na sidebar cria um novo tileset em branco com slots A1-E vazios",
        "Botão 'Delete' remove o tileset selecionado com confirmação, preservando IDs estáveis",
        "Nova chave i18n btn.new adicionada em todos os 5 locales",
      ],
   },
   {
      date: "June 17, 2026",
      title: "Correção do Sistema de Flags RMMV — Engine-compatible Bit Layout",
      summary: "Bit layout de flags corrigido para corresponder exatamente ao engine RMMV (rpg_objects.js): direções nos bits 0-3, star no bit 4, ladder/bush/counter/damage nos bits 5-8, terrain tag nos bits 12-15. Flag offsets e tile IDs alinhados com as constantes do engine (TILE_ID_*).",
      items: [
        "RMMV_FLAGS redefinido com bit layout do engine: DIR_DOWN(0x01), DIR_LEFT(0x02), DIR_RIGHT(0x04), DIR_UP(0x08), STAR(0x10), LADDER(0x20), BUSH(0x40), COUNTER(0x80), DAMAGE(0x100), terrain tag >>12",
        "RMMV_FLAG_OFFSETS corrigido: A1=2048, A2=2816, A3=4352, A4=5888, A5=1536, B=0, C=256, D=512, E=768",
        "getRmmvTileFlags/setRmmvTileFlags agora indexam por tileId diretamente (sem -2048)",
        "decodeTileId reescrito para usar ranges do engine (B: 0-255, C: 256-511, ..., A4: 5888-8191)",
        "Editor expandido de 5 para 9 abas (A1..A5 + B..E) — cada categoria tem sua aba",
        "calculateNextFlagState, drawFlags e onCanvasDown corrigidos para o novo bit layout",
        "rmmvToLegacyFlag e legacyMaskToRmmv atualizados para conversão correta"
      ],
   },
   {
      date: "June 17, 2026",
      title: "Tileset Editor Refactor + Engine RMMV + StorageService",
      summary: "Editor de tilesets refatorado com layout RMMV (5 colunas, tools verticais com labels completos), playtest agora usa o engine RMMV v1.6.2, nova camada de abstração de I/O (StorageService) e correção de overlays.",
      items: [
        "Nova coluna de ferramentas à direita com 7 botões: Passagem, Passagem (4 dir.), Escada, Arbusto, Balcão, Dano no Terreno, Tag de Terreno",
        "Campo de notas (textarea) para cada tileset com i18n",
        "Overlays dinâmicos no visualizador: ○, ×, ★ (só B-E), setas, ESC, ARB, BAL, DNO, tags 0-7 amarelas",
        "Clique por zona na ferramenta Passagem (4 dir.) para alternar direções individuais",
        "Playtest agora usa o engine RPG Maker MV v1.6.2 (rpg_core.js, rpg_managers.js, etc.) com bridge script",
        "StorageService: nova abstração de I/O compatível com Tauri e Web (fetch/download)",
        "Novos comandos Rust: list_directory, read_text_file, write_text_file, read_file_base64"
      ],
   },
   {
      date: "June 17, 2026",
      title: t("patch_notes.title.36"),
      summary: t("patch_notes.summary.36"),
      items: [
        t("patch_notes.item.36.1"),
        t("patch_notes.item.36.2"),
        t("patch_notes.item.36.3"),
        t("patch_notes.item.36.4"),
        t("patch_notes.item.36.5"),
      ],
   },
   {
      date: "June 17, 2026",
      title: t("patch_notes.title.35"),
      summary: t("patch_notes.summary.35"),
      items: [
        t("patch_notes.item.35.1"),
        t("patch_notes.item.35.2"),
        t("patch_notes.item.35.3"),
        t("patch_notes.item.35.4"),
      ],
   },
   {
      date: "June 17, 2026",
      title: t("patch_notes.title.34"),
      summary: t("patch_notes.summary.34"),
      items: [
        t("patch_notes.item.34.1"),
        t("patch_notes.item.34.2"),
        t("patch_notes.item.34.3"),
        t("patch_notes.item.34.4"),
        t("patch_notes.item.34.5"),
      ],
   },
   {
      date: "June 17, 2026",
      title: t("patch_notes.title.33"),
      summary: t("patch_notes.summary.33"),
      items: [
        t("patch_notes.item.33.1"),
        t("patch_notes.item.33.2"),
        t("patch_notes.item.33.3"),
        t("patch_notes.item.33.4"),
        t("patch_notes.item.33.5"),
        t("patch_notes.item.33.6"),
      ],
   },
   {
      date: "June 16, 2026",
      title: t("patch_notes.title.0"),
      summary: t("patch_notes.summary.0"),
      items: [
        t("patch_notes.item.0.1"),
        t("patch_notes.item.0.2"),
        t("patch_notes.item.0.3"),
        t("patch_notes.item.0.4"),
        t("patch_notes.item.0.5"),
        t("patch_notes.item.0.6"),
      ],
   },
   {
      date: "June 16, 2026",
      title: t("patch_notes.title.1"),
      summary: t("patch_notes.summary.1"),
      items: [],
   },
   {
      date: "June 16, 2026",
      title: t("patch_notes.title.2"),
      summary: t("patch_notes.summary.2"),
      items: [],
   },
   {
      date: "June 15, 2026",
      title: t("patch_notes.title.3"),
     summary: t("patch_notes.summary.3"),
     items: [],
   },
   {
     date: "June 15, 2026",
     title: t("patch_notes.title.4"),
     summary: t("patch_notes.summary.4"),
     items: [],
   },
   {
     date: "June 15, 2026",
     title: t("patch_notes.title.5"),
     summary: t("patch_notes.summary.5"),
     items: [],
   },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.6"),
    summary: t("patch_notes.summary.6"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.7"),
    summary: t("patch_notes.summary.7"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.8"),
    summary: t("patch_notes.summary.8"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.9"),
    summary: t("patch_notes.summary.9"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.10"),
    summary: t("patch_notes.summary.10"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.11"),
    summary: t("patch_notes.summary.11"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.12"),
    summary: t("patch_notes.summary.12"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.13"),
    summary: t("patch_notes.summary.13"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.14"),
    summary: t("patch_notes.summary.14"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.15"),
    summary: t("patch_notes.summary.15"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.16"),
    summary: t("patch_notes.summary.16"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.17"),
    summary: t("patch_notes.summary.17"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.18"),
    summary: t("patch_notes.summary.18"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.19"),
    summary: t("patch_notes.summary.19"),
    items: [],
  },
  {
    date: "June 14, 2026",
    title: t("patch_notes.title.20"),
    summary: t("patch_notes.summary.20"),
    items: [],
  },
  {
    date: "June 14, 2026",
    title: t("patch_notes.title.21"),
    summary: t("patch_notes.summary.21"),
    items: [],
  },
  {
    date: "June 14, 2026",
    title: t("patch_notes.title.22"),
    summary: t("patch_notes.summary.22"),
    items: [],
  },
  {
    date: "June 14, 2026",
    title: t("patch_notes.title.23"),
    summary: t("patch_notes.summary.23"),
    items: [],
  },
  {
    date: "June 14, 2026",
    title: t("patch_notes.title.24"),
    summary: t("patch_notes.summary.24"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.25"),
    summary: t("patch_notes.summary.25"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.26"),
    summary: t("patch_notes.summary.26"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.27"),
    summary: t("patch_notes.summary.27"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.28"),
    summary: t("patch_notes.summary.28"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.29"),
    summary: t("patch_notes.summary.29"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.30"),
    summary: t("patch_notes.summary.30"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.31"),
    summary: t("patch_notes.summary.31"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.32"),
    summary: t("patch_notes.summary.32"),
    items: [],
  },
  ];
}
