/* RPGAtlas - patch-notes.js
   Keep newest entries first. See AGENTS.md for the update policy. */
"use strict";

export function getPatchNotes(t) {
  return [
   {
      date: "June 17, 2026",
      title: t("patch_notes.title.35"),
      summary: t("patch_notes.summary.35"),
      items: [
        t("patch_notes.item.35.1"),
        t("patch_notes.item.35.2"),
        t("patch_notes.item.35.3"),
        t("patch_notes.item.35.4"),
      ],
   },
   {
      date: "June 17, 2026",
      title: t("patch_notes.title.34"),
      summary: t("patch_notes.summary.34"),
      items: [
        t("patch_notes.item.34.1"),
        t("patch_notes.item.34.2"),
        t("patch_notes.item.34.3"),
        t("patch_notes.item.34.4"),
        t("patch_notes.item.34.5"),
      ],
   },
   {
      date: "June 17, 2026",
      title: t("patch_notes.title.33"),
      summary: t("patch_notes.summary.33"),
      items: [
        t("patch_notes.item.33.1"),
        t("patch_notes.item.33.2"),
        t("patch_notes.item.33.3"),
        t("patch_notes.item.33.4"),
        t("patch_notes.item.33.5"),
        t("patch_notes.item.33.6"),
      ],
   },
   {
      date: "June 16, 2026",
      title: t("patch_notes.title.0"),
      summary: t("patch_notes.summary.0"),
      items: [
        t("patch_notes.item.0.1"),
        t("patch_notes.item.0.2"),
        t("patch_notes.item.0.3"),
        t("patch_notes.item.0.4"),
        t("patch_notes.item.0.5"),
        t("patch_notes.item.0.6"),
      ],
   },
   {
      date: "June 16, 2026",
      title: t("patch_notes.title.1"),
      summary: t("patch_notes.summary.1"),
      items: [],
   },
   {
      date: "June 16, 2026",
      title: t("patch_notes.title.2"),
      summary: t("patch_notes.summary.2"),
      items: [],
   },
   {
      date: "June 15, 2026",
      title: t("patch_notes.title.3"),
     summary: t("patch_notes.summary.3"),
     items: [],
   },
   {
     date: "June 15, 2026",
     title: t("patch_notes.title.4"),
     summary: t("patch_notes.summary.4"),
     items: [],
   },
   {
     date: "June 15, 2026",
     title: t("patch_notes.title.5"),
     summary: t("patch_notes.summary.5"),
     items: [],
   },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.6"),
    summary: t("patch_notes.summary.6"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.7"),
    summary: t("patch_notes.summary.7"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.8"),
    summary: t("patch_notes.summary.8"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.9"),
    summary: t("patch_notes.summary.9"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.10"),
    summary: t("patch_notes.summary.10"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.11"),
    summary: t("patch_notes.summary.11"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.12"),
    summary: t("patch_notes.summary.12"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.13"),
    summary: t("patch_notes.summary.13"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.14"),
    summary: t("patch_notes.summary.14"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.15"),
    summary: t("patch_notes.summary.15"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.16"),
    summary: t("patch_notes.summary.16"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.17"),
    summary: t("patch_notes.summary.17"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.18"),
    summary: t("patch_notes.summary.18"),
    items: [],
  },
  {
    date: "June 15, 2026",
    title: t("patch_notes.title.19"),
    summary: t("patch_notes.summary.19"),
    items: [],
  },
  {
    date: "June 14, 2026",
    title: t("patch_notes.title.20"),
    summary: t("patch_notes.summary.20"),
    items: [],
  },
  {
    date: "June 14, 2026",
    title: t("patch_notes.title.21"),
    summary: t("patch_notes.summary.21"),
    items: [],
  },
  {
    date: "June 14, 2026",
    title: t("patch_notes.title.22"),
    summary: t("patch_notes.summary.22"),
    items: [],
  },
  {
    date: "June 14, 2026",
    title: t("patch_notes.title.23"),
    summary: t("patch_notes.summary.23"),
    items: [],
  },
  {
    date: "June 14, 2026",
    title: t("patch_notes.title.24"),
    summary: t("patch_notes.summary.24"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.25"),
    summary: t("patch_notes.summary.25"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.26"),
    summary: t("patch_notes.summary.26"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.27"),
    summary: t("patch_notes.summary.27"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.28"),
    summary: t("patch_notes.summary.28"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.29"),
    summary: t("patch_notes.summary.29"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.30"),
    summary: t("patch_notes.summary.30"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.31"),
    summary: t("patch_notes.summary.31"),
    items: [],
  },
  {
    date: "June 13, 2026",
    title: t("patch_notes.title.32"),
    summary: t("patch_notes.summary.32"),
    items: [],
  },
  ];
}
